// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI1Q29hzuaGi-_x6Ay6nyNXRIJ8p-KFZI',
    appId: '1:227816005800:web:5c058c2e743035d1a7229d',
    messagingSenderId: '227816005800',
    projectId: 'spot-975f2',
    authDomain: 'spot-975f2.firebaseapp.com',
    storageBucket: 'spot-975f2.firebasestorage.app',
    measurementId: 'G-RW1NSK24PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2QkT0vkdMWdG7abH10hQKg_e84uq0600',
    appId: '1:227816005800:android:edbccf191206db8fa7229d',
    messagingSenderId: '227816005800',
    projectId: 'spot-975f2',
    storageBucket: 'spot-975f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO67qcKffW2lQSnEcKbY2t3tkkulYvzpE',
    appId: '1:227816005800:ios:5bafd6c4dc4f72a8a7229d',
    messagingSenderId: '227816005800',
    projectId: 'spot-975f2',
    storageBucket: 'spot-975f2.firebasestorage.app',
    iosBundleId: 'com.example.spot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO67qcKffW2lQSnEcKbY2t3tkkulYvzpE',
    appId: '1:227816005800:ios:5bafd6c4dc4f72a8a7229d',
    messagingSenderId: '227816005800',
    projectId: 'spot-975f2',
    storageBucket: 'spot-975f2.firebasestorage.app',
    iosBundleId: 'com.example.spot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI1Q29hzuaGi-_x6Ay6nyNXRIJ8p-KFZI',
    appId: '1:227816005800:web:15bef53acd0fde63a7229d',
    messagingSenderId: '227816005800',
    projectId: 'spot-975f2',
    authDomain: 'spot-975f2.firebaseapp.com',
    storageBucket: 'spot-975f2.firebasestorage.app',
    measurementId: 'G-9R7MZTRNHP',
  );
}
